print ("Введите ФИО:")
FIO = input()
print("Введите факультет:")
FAC = input()
print ("Введите курс:")
COURSE = input()
print ("Введите группу:")
GROUP = input()
print ("Введите E-Mail:")
EMAIL = input()
print ("Студент(-ка)", FIO, "Обучается на факультете", FAC, ",на", COURSE, "курсе", "в группе", GROUP, ",E-Mail", EMAIL, end='')